# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectProductWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# main again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 200)
        Form.setMaximumSize(QtCore.QSize(420, 280))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(40, 140, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 140, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_0 = QtWidgets.QComboBox(Form)
        self.comboBox_0.setGeometry(QtCore.QRect(110, 60, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_0.setFont(font)
        self.comboBox_0.setObjectName("comboBox_0")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.comboBox_0.addItem("")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(30, 60, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_0 = QtWidgets.QLabel(Form)
        self.label_0.setGeometry(QtCore.QRect(30, 10, 260, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_0.setFont(font)
        self.label_0.setText("")
        self.label_0.setObjectName("label_0")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "产品选择"))
        self.pushButton_1.setText(_translate("Form", "确认"))
        self.pushButton_2.setText(_translate("Form", "取消"))
        self.comboBox_0.setItemText(0, _translate("Form", "默认产品"))
        self.comboBox_0.setItemText(1, _translate("Form", "新建项目"))
        self.comboBox_0.setItemText(2, _translate("Form", "新建项目"))
        self.comboBox_0.setItemText(3, _translate("Form", "新建项目"))
        self.comboBox_0.setItemText(4, _translate("Form", "新建项目"))
        self.comboBox_0.setItemText(5, _translate("Form", "新建项目"))
        self.comboBox_0.setItemText(6, _translate("Form", "新建项目"))
        self.comboBox_0.setItemText(7, _translate("Form", "新建项目"))
        self.comboBox_0.setItemText(8, _translate("Form", "新建项目"))
        self.comboBox_0.setItemText(9, _translate("Form", "新建项目"))
        self.comboBox_0.setItemText(10, _translate("Form", "新建项目10"))
        self.label_1.setText(_translate("Form", "更改产品"))
